/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Anan
 */
public class Tambah extends javax.swing.JPanel {

    /**
     * Creates new form Tambah
     */
    public Tambah() {
        initComponents();
    }
                         

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_kode = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_nama = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_kategori = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_deskripsi = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_lokasi = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_tanggal = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel3.setBackground(new java.awt.Color(93, 218, 19));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Kode");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));
        jPanel3.add(txt_kode, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 17, 283, 28));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Nama Dokumen");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));
        jPanel3.add(txt_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 51, 283, 28));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Kategori");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, -1, -1));
        jPanel3.add(txt_kategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 85, 283, 28));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Deskripsi");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, -1, -1));
        jPanel3.add(txt_deskripsi, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 119, 283, 28));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Lokasi");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, -1));
        jPanel3.add(txt_lokasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 153, 283, 28));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Tanggal");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, -1, -1));
        jPanel3.add(txt_tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 187, 283, 28));

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        jPanel3.add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 265, -1, -1));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 56;
        gridBagConstraints.ipady = 51;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(62, 113, 67, 109);
        jPanel1.add(jPanel3, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 762, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        String kode = txt_kode.getText();
        String nama = txt_nama.getText();
        String kategori = txt_kategori.getText();
        String deskripsi = txt_deskripsi.getText();
        String lokasi = txt_lokasi.getText();
        String tanggal = txt_tanggal.getText();
        
        if(kode.isEmpty()){
            JOptionPane.showMessageDialog(this, "Kode harus diisi");
            txt_kode.requestFocus();
        }else if(nama.isEmpty()){
            JOptionPane.showMessageDialog(this, "Nama Dokumen harus diisi");
            txt_nama.requestFocus();
        }else if(kategori.isEmpty()){
            JOptionPane.showMessageDialog(this, "Kategori harus diisi");
            txt_kategori.requestFocus();
        }else if(deskripsi.isEmpty()){
            JOptionPane.showMessageDialog(this, "Deskripsi harus diisi");
            txt_deskripsi.requestFocus();
        }else if(lokasi.isEmpty()){
            JOptionPane.showMessageDialog(this, "Lokasi harus diisi");
            txt_lokasi.requestFocus();
        }else if(tanggal.isEmpty()){
            JOptionPane.showMessageDialog(this, "Tanggal dibuat harus diisi");
            txt_tanggal.requestFocus();
        }else{
            try {
                Connection c = Koneksi.MySQL();
                String q = "INSERT INTO data (kode, nama, kategori, lokasi, deskripsi, tanggal) VALUES (?,?,?,?,?,?)";
                PreparedStatement ps = c.prepareStatement(q);
                ps.setString(1, kode);
                ps.setString(2, nama);
                ps.setString(3, kategori);
                ps.setString(4, lokasi);
                ps.setString(5, deskripsi);
                ps.setString(6, tanggal);
                ps.execute();
                JOptionPane.showMessageDialog(this, "Berhasil");
                Home.panggilPanel(new Data());
                
            } catch (HeadlessException | SQLException e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
    }//GEN-LAST:event_btnSimpanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSimpan;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txt_deskripsi;
    private javax.swing.JTextField txt_kategori;
    private javax.swing.JTextField txt_kode;
    private javax.swing.JTextField txt_lokasi;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_tanggal;
    // End of variables declaration//GEN-END:variables
}
